services:
  opensips:
    image: opensips:latest
    container_name: opensips
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "5061:5061/tcp"
    volumes:
      # Mount configuration directory (optional - uncomment to use custom config)
      # - ./etc/opensips:/usr/local/etc/opensips
      # Mount logs directory (optional)
      - opensips-logs:/var/log/opensips
    # Uncomment to run as non-root (requires config changes)
    # user: opensips
    restart: unless-stopped
    # You can override the default command for debugging
    # command: ["opensips", "-F", "-DD"]  # -DD for debug level 2

volumes:
  opensips-logs:

